
- name: (linux) Install falcon-sensor
  hosts: linux
  vars:
    home_path: "/home/ssm-user"
    pkg_bucket: "{{ lookup('ansible.builtin.env', 'CROWDSTRIKE_BUCKET') }}"
    pkg_manager_type: "{{ ansible_pkg_mgr }}"
    pkg_name: "{{ tags.crowdstrike_package_name }}"
    pkg_path_controller: "/srv/newrelic/fluent-bit-package/{{ pkg_bucket }}/{{ pkg_name }}"
    pkg_path_remote: "{{ home_path }}/{{ pkg_name }}"
    ccid: "{{ lookup('ansible.builtin.env', 'CROWDSTRIKE_CCID') }}"
  tasks:
    - name: Wait for connection to be available
      wait_for_connection:

    - name: (linux) Copy falcon-sensor package
      ansible.builtin.copy:
        src: "{{ pkg_path_controller }}"
        dest: "{{ pkg_path_remote }}"

    - name: (apt) Install falcon-sensor
      when: pkg_manager_type == 'apt'
      become: true
      ansible.builtin.apt:
        deb: "{{ pkg_path_remote }}"
        # crowdstrike packages are not signed
        allow_unauthenticated: true

    - name: (yum) Install falcon-sensor
      when: pkg_manager_type == 'yum'
      become: true
      ansible.builtin.yum:
        name: "{{ pkg_path_remote }}"
        # crowdstrike packages are not signed
        disable_gpg_check: true

    - name: (dnf) Install falcon-sensor
      when: pkg_manager_type == 'dnf'
      become: true
      ansible.builtin.dnf:
        name: "{{ pkg_path_remote }}"
        # crowdstrike packages are not signed
        disable_gpg_check: true

    - name: (zypper) Install falcon-sensor
      when: pkg_manager_type == 'zypper'
      become: true
      community.general.zypper:
        name: "{{ pkg_path_remote }}"
        # crowdstrike packages are not signed
        disable_gpg_check: true
      environment:
        ZYPP_LOCK_TIMEOUT: 300

    - name: (linux) Configure falcon-sensor
      become: true
      ansible.builtin.command:
        argv:
          - "/opt/CrowdStrike/falconctl"
          - "-s"
          - "-f"
          - "--cid={{ ccid }}"

    - name: (linux) Enable and start falcon
      become: true
      ansible.builtin.service:
        state: started
        enabled: true
        name: falcon-sensor

- name: (windows) Install falcon-sensor
  hosts: windows
  vars:
    home_path: 'C:\Tmp'
    pkg_bucket: "{{ lookup('ansible.builtin.env', 'CROWDSTRIKE_BUCKET') }}"
    pkg_manager_type: "{{ ansible_pkg_mgr }}"
    pkg_name: "{{ tags.crowdstrike_package_name }}"
    pkg_path_controller: "/srv/newrelic/fluent-bit-package/{{ pkg_bucket }}/{{ pkg_name }}"
    pkg_path_remote: '{{ home_path }}\{{ pkg_name }}'
    ccid: "{{ lookup('ansible.builtin.env', 'CROWDSTRIKE_CCID') }}"
  tasks:
    - name: (windows) Copy falcon-sensor package
      ansible.windows.win_copy:
        src: '{{ pkg_path_controller }}'
        dest: '{{ pkg_path_remote }}'

    - name: (windows) Install falcon-sensor
      ansible.windows.win_command:
        cmd: '{{ pkg_path_remote }} /install /quiet /norestart CID={{ ccid }}'
