- name: Load Linux variables
  ansible.builtin.include_vars: "linux.yml"

- name: Stop newrelic-infra service
  ansible.builtin.service:
    name: newrelic-infra
    state: stopped
  become: true

- name: Download NR FB Output Plugin
  ansible.builtin.get_url:
    url: "{{ nr_fb_output_plugin_url }}"
    dest: "{{ nr_fb_output_plugin_download_file_path }}"

- name: Modify Infrastructure Agent config to point to downloaded NR FB Output Plugin
  ansible.builtin.lineinfile:
    path: "{{ infra_agent_config_file_absolute_path }}"
    line: 'fluent_bit_nr_lib_path: {{ nr_fb_output_plugin_download_file_path }}'
  become: true

- name: Start again newrelic-infra service with new NR FB Output plugin
  ansible.builtin.service:
    name: newrelic-infra
    state: started
  become: true