- name: Load a variable file based on the OS type
  ansible.builtin.include_vars: "windows.yml"

- name: Stop newrelic-infra service (Windows)
  ansible.windows.win_service:
    name: newrelic-infra
    state: stopped

- name: Download NR FB Output Plugin
  ansible.windows.win_get_url:
    url: "{{ nr_fb_output_plugin_url }}"
    dest: '{{ nr_fb_output_plugin_download_file_path }}'

- name: Modify Infrastructure Agent config to point to downloaded NR FB Output Plugin
  community.windows.win_lineinfile:
    path: "{{ infra_agent_config_file_absolute_path }}"
    line: 'fluent_bit_nr_lib_path: {{ nr_fb_output_plugin_download_file_path }}'

- name: Start again newrelic-infra service with new NR FB Output plugin (Windows)
  ansible.windows.win_service:
    name: newrelic-infra
    state: started