fb_package_url: "https://github.com/newrelic/fluent-bit-package/releases/download/{{ gh_prerelease_tag }}/{{ fb_package_name }}"
fb_binary_path: C:\Applications\FluentBit
nr_fb_output_plugin_artifact: 'out_newrelic-windows-{{ arch }}-{{ nr_fb_output_plugin_version }}.dll'
nr_fb_output_plugin_url: "https://github.com/newrelic/newrelic-fluent-bit-output/releases/download/v{{ nr_fb_output_plugin_version }}/{{ nr_fb_output_plugin_artifact }}"