name: Spin Up test Executors

on:
  # To be able to launch it from pull_request.yml programmatically
  workflow_call:
    inputs:
      gh_release_name:
        description: GitHub release name containing Fluent Bit packages
        required: false
        default: latest
        type: string
      infra_agent_env:
        description: Repository used to download infra-agent
        required: false
        default: staging
        type: string  # To be able to launch it from the Actions UI, on-demand
  workflow_dispatch:
    inputs:
      gh_release_name:
        description: GitHub release name containing Fluent Bit packages
        required: false
        default: latest
        type: string
      infra_agent_env:
        description: Repository used to download infra-agent
        required: false
        default: production
        type: string  # To be able to launch it from the Actions UI, on-demand

jobs:
  spin_up_test_executor_instances:
    name: Spin up test executor instances
    uses: ./.github/workflows/run_task.yml
    with:
      container_make_target: "terraform/ec2-test-executors/${{ inputs.infra_agent_env }} PRE_RELEASE_NAME=${{ inputs.gh_release_name }}"
    secrets: inherit
