name: Spin Up test Executors

on:
  # To be able to launch it from pull_request.yml programmatically
  workflow_call:
    inputs:
      gh_release_name:
        description: GitHub release name containing Fluent Bit packages
        required: false
        default: latest
        type: string
  workflow_dispatch:
    inputs:
      gh_release_name:
        description: GitHub release name containing Fluent Bit packages
        required: false
        default: latest
        type: string

jobs:
  tear_down_test_executor_instances:
    name: Tear down test executor instances
    uses: ./.github/workflows/run_task.yml
    with:
      container_make_target: "terraform/ec2-test-executors/clean PRE_RELEASE_NAME=${{ inputs.gh_release_name }}"
    secrets: inherit
